name: Deploy Backend to EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd backend/forestFireAdmin_back/app

            echo "NODE_ENV=dev" > .env
            echo "PORT=3002" >> .env
            echo "DB_HOST=forest-fire.cbm06os0m2be.ap-northeast-2.rds.amazonaws.com" >> .env
            echo "DB_USER=admin" >> .env
            echo "DB_PASSWORD=rladmsdn11!" >> .env
            echo "DB_DATABASE=fire_forest" >> .env
            echo "ADMIN_PASSKEY=ce404" >> .env

            git pull origin develop

            sudo docker stop forest-back || true
            sudo docker rm forest-back || true

            sudo docker build -t forest-back .
            sudo docker run -d -p 3002:3002 --name forest-back forest-back
